server:
  port: 8082
spring:
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    encoding: UTF-8
  resources:
    static-locations: classpath:/META-INF/resouces/,classpath:/resoures/
  data:
    mongodb:
      #uri: mongodb://admin@47.106.77.86:27017/?authSource=invite
      username: admin
      password: admin123
      host: 47.106.77.86
      port: 27017
    elasticsearch:
      cluster-name: test-elasticsearch
      cluster-nodes: 47.106.77.86:9300
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: canal
    password: canal
    url: jdbc:mysql://47.106.77.86:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
  redis:
    host: 47.106.77.86
    password: redispass
    database: 0
    timeout: 2000 #连接超时时间(毫秒)
    port: 6379
    jedis:
      pool:
        max-active: 8 #连接池最大连接数(负值表示没有限制)
        max-wait: -1  # 连接池最大阻塞等待时间（负值表示没有限制）
        max-idle: 8 #连接池最大空闲连接
        min-idle: 0 #连接池最小空闲连接
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: 192.168.1.202
    port: 5672
    username: superadmin
    password: superadmin
    virtual-host: /test01
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/**.xml
